server:
  port: 9001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1657486787/mk-config-center  #或者  https://github.com/1657486787/mk-config-center.git
          username:
          password:
